/**
 * Professional Construction Reporting Engine - Data Extraction & CSV Generators
 * Supports 24 Standardized Indian Government Contractor Reports.
 */

import { SupabaseClient } from '@supabase/supabase-js'
import {
  ReportKey,
  ReportResult,
  ReportFilterParams,
  ReportMetadata,
  REPORT_REGISTRY,
} from './types'
import { escapeCsvCell } from '../export/csv'
import { formatDate } from '../format'

/**
 * Format Indian Currency for Report Display
 */
export function formatReportCurrency(amount: number | null | undefined): string {
  if (amount === null || amount === undefined || isNaN(amount)) return '₹0.00'
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
  }).format(amount)
}

/**
 * Format Indian Numeric Quantity
 */
export function formatReportNumber(num: number | null | undefined, decimals = 3): string {
  if (num === null || num === undefined || isNaN(num)) return '0.000'
  return new Intl.NumberFormat('en-IN', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  }).format(num)
}

/**
 * Generates an RFC-4180 UTF-8 BOM CSV for any of the 24 reports, including metadata headers.
 */
export function generateReportCsv(report: ReportResult): string {
  const metaLines: string[][] = [
    ['PILLARPRO GOVERNMENT CONTRACTOR REPORTING ENGINE', ''],
    ['REPORT TITLE', report.reportTitle],
    ['PROJECT', report.metadata.projectName],
    ['CONTRACT / AGREEMENT', report.metadata.agreementNumber || 'N/A'],
    ['EMPLOYING AGENCY', report.metadata.employerName || report.metadata.agencyName],
    ['DIVISION / CIRCLE', report.metadata.division || 'N/A'],
    ['REPORTING PERIOD', report.metadata.reportingPeriod],
    ['GENERATED ON', report.metadata.generatedAt],
    ['GENERATED BY', `${report.metadata.generatedByName} (${report.metadata.generatedByRole})`],
    ['', ''], // blank spacer
  ]

  const headers = report.columns.map(c => c.label)
  const dataRows: (string | number | boolean | null | undefined)[][] = report.rows.map(row => {
    return report.columns.map(col => {
      const val = row[col.key]
      if (val === null || val === undefined) return '-'
      if (col.format === 'currency') return formatReportCurrency(Number(val))
      if (col.format === 'number') return formatReportNumber(Number(val))
      if (col.format === 'percent') return `${Number(val).toFixed(2)}%`
      if (col.format === 'date') return formatDate(String(val))
      return String(val)
    })
  })

  // Append Totals Row if present
  if (report.totals && Object.keys(report.totals).length > 0) {
    const totalRow = report.columns.map((col, idx) => {
      if (idx === 0) return 'GRAND TOTAL'
      const totalVal = report.totals?.[col.key]
      if (totalVal !== undefined && totalVal !== null) {
        if (col.format === 'currency') return formatReportCurrency(Number(totalVal))
        if (col.format === 'number') return formatReportNumber(Number(totalVal))
        if (col.format === 'percent') return `${Number(totalVal).toFixed(2)}%`
        return String(totalVal)
      }
      return ''
    })
    dataRows.push(totalRow)
  }

  // Append Signoff Attestation Block
  dataRows.push(['', ''])
  dataRows.push(['ATTESTATION & SIGN-OFF BLOCK', ''])
  dataRows.push(['Prepared By', report.metadata.preparedByTitle, '', 'Checked By', report.metadata.checkedByTitle, '', 'Approved By', report.metadata.approvedByTitle])
  dataRows.push(['Signature & Date', '___________________', '', 'Signature & Date', '___________________', '', 'Authorized Seal', '___________________'])

  const allRows = [...metaLines, headers, ...dataRows]
  return '\uFEFF' + allRows.map(row => row.map(escapeCsvCell).join(',')).join('\r\n')
}

/**
 * Fetch and construct metadata header for the report.
 */
async function resolveReportMetadata(
  supabase: SupabaseClient,
  projectId?: string,
  userProfile?: any,
  startDate?: string,
  endDate?: string
): Promise<{ metadata: ReportMetadata; projectData?: any; contractData?: any }> {
  let projectData: any = null
  let contractData: any = null

  if (projectId && projectId !== 'all') {
    const { data: proj } = await supabase
      .from('projects')
      .select('id, name, agency_name, awarded_amount, start_date, end_date')
      .eq('id', projectId)
      .single()
    projectData = proj

    const { data: contract } = await supabase
      .from('contracts')
      .select('id, agreement_number, employer_name, division, circle, awarded_amount, current_completion_date, original_completion_date')
      .eq('project_id', projectId)
      .order('is_primary', { ascending: false })
      .limit(1)
      .maybeSingle()
    contractData = contract
  }

  const periodLabel = startDate && endDate
    ? `From ${formatDate(startDate)} to ${formatDate(endDate)}`
    : startDate
    ? `From ${formatDate(startDate)} onwards`
    : endDate
    ? `Up to ${formatDate(endDate)}`
    : 'All Dates to Present'

  const now = new Date()
  const generatedAt = new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: 'Asia/Kolkata',
  }).format(now) + ' IST'

  const metadata: ReportMetadata = {
    projectId: projectData?.id || null,
    projectName: projectData?.name || 'All Active Firm Projects',
    agencyName: projectData?.agency_name || 'Government Works Department',
    contractId: contractData?.id || null,
    agreementNumber: contractData?.agreement_number || 'General Project Scope',
    employerName: contractData?.employer_name || projectData?.agency_name || 'Department of Public Works',
    division: contractData?.division ? `${contractData.division}${contractData.circle ? `, ${contractData.circle}` : ''}` : 'Executive Engineering Division',
    reportingPeriod: periodLabel,
    periodStart: startDate || null,
    periodEnd: endDate || null,
    generatedAt,
    generatedByName: userProfile?.display_name || userProfile?.name || 'Authorized Engineer',
    generatedByEmail: userProfile?.email || 'engineer@pillarpro.in',
    generatedByRole: (userProfile?.role || 'Staff').toUpperCase().replace(/_/g, ' '),
    preparedByTitle: 'Site Engineer (Incharge)',
    checkedByTitle: 'Billing Engineer / QS',
    approvedByTitle: 'Authorized Signatory / Contractor',
    departmentStandardNotice: 'Universal Standard Construction Format — Neutral Indian Public Works Standard',
  }

  return { metadata, projectData, contractData }
}

/**
 * Master Data Fetcher & Formatter for all 24 Reports
 */
export async function fetchReportData(
  supabase: SupabaseClient,
  params: ReportFilterParams,
  userProfile?: any
): Promise<ReportResult> {
  const { reportKey, projectId, startDate, endDate, status } = params
  const def = REPORT_REGISTRY[reportKey] || REPORT_REGISTRY.MEASUREMENT_BOOK

  const { metadata, projectData } = await resolveReportMetadata(
    supabase,
    projectId,
    userProfile,
    startDate,
    endDate
  )

  metadata.preparedByTitle = def.applicableSignoffs.preparedBy
  metadata.checkedByTitle = def.applicableSignoffs.checkedBy
  metadata.approvedByTitle = def.applicableSignoffs.approvedBy

  switch (reportKey) {
    // ─────────────────────────────────────────────────────────────────────────
    // 1. MEASUREMENT BOOK (e-MB DETAIL RECORD)
    // ─────────────────────────────────────────────────────────────────────────
    case 'MEASUREMENT_BOOK': {
      let query = supabase
        .from('measurement_entries')
        .select(`
          id, entry_number, measurement_date, description, location, chainage_km, chainage_m,
          calculation_mode, number_of_units, length, breadth, depth_height, calculated_quantity,
          unit, status, entered_by, checked_by, certified_by,
          boq_items ( item_number, description )
        `)
        .order('measurement_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('measurement_date', startDate)
      if (endDate) query = query.lte('measurement_date', endDate)
      if (status && status !== 'ALL') query = query.eq('status', status)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'entry_number', label: 'MB Entry No', align: 'left' as const },
        { key: 'measurement_date', label: 'Date', format: 'date' as const, align: 'center' as const },
        { key: 'boq_item', label: 'BOQ Item', align: 'left' as const },
        { key: 'location', label: 'Location / Chainage', align: 'left' as const },
        { key: 'description', label: 'Work Description', align: 'left' as const },
        { key: 'units_count', label: 'No', format: 'number' as const, align: 'right' as const },
        { key: 'length', label: 'L (m)', format: 'number' as const, align: 'right' as const },
        { key: 'breadth', label: 'B (m)', format: 'number' as const, align: 'right' as const },
        { key: 'depth_height', label: 'D/H (m)', format: 'number' as const, align: 'right' as const },
        { key: 'calculated_quantity', label: 'Calculated Qty', format: 'number' as const, align: 'right' as const },
        { key: 'unit', label: 'Unit', align: 'center' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
        { key: 'certified_by', label: 'Certified By', align: 'left' as const },
      ]

      const rows = rawRows.map((r: any) => ({
        entry_number: r.entry_number,
        measurement_date: r.measurement_date,
        boq_item: r.boq_items?.item_number ? `#${r.boq_items.item_number}` : '-',
        location: r.chainage_km ? `Km ${r.chainage_km}+${r.chainage_m || 0}` : (r.location || '-'),
        description: r.description,
        units_count: r.number_of_units || 1,
        length: r.length || 0,
        breadth: r.breadth || 0,
        depth_height: r.depth_height || 0,
        calculated_quantity: Number(r.calculated_quantity) || 0,
        unit: r.unit || 'cum',
        status: r.status || 'DRAFT',
        certified_by: r.certified_by || r.entered_by || '-',
      }))

      const totalQty = rows.reduce((s, r) => s + (Number(r.calculated_quantity) || 0), 0)

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { calculated_quantity: totalQty },
        availableStatuses: ['ALL', 'DRAFT', 'SUBMITTED', 'CHECKED', 'CERTIFIED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 2. ABSTRACT OF MEASUREMENTS
    // ─────────────────────────────────────────────────────────────────────────
    case 'ABSTRACT_OF_MEASUREMENTS': {
      let boqQuery = supabase
        .from('boq_items')
        .select(`
          id, item_number, description, unit, tender_quantity, awarded_rate, total_amount,
          certified_quantity, measured_quantity
        `)
        .order('item_number')

      if (projectId && projectId !== 'all') boqQuery = boqQuery.eq('project_id', projectId)

      const { data: boqData } = await boqQuery
      const rawRows = boqData || []

      const columns = [
        { key: 'item_number', label: 'Item No', align: 'left' as const },
        { key: 'description', label: 'Item Description', align: 'left' as const },
        { key: 'unit', label: 'Unit', align: 'center' as const },
        { key: 'tender_quantity', label: 'Tender Qty', format: 'number' as const, align: 'right' as const },
        { key: 'awarded_rate', label: 'Tender Rate', format: 'currency' as const, align: 'right' as const },
        { key: 'certified_quantity', label: 'Certified Qty to Date', format: 'number' as const, align: 'right' as const },
        { key: 'certified_amount', label: 'Amount Certified (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'execution_percent', label: '% Executed', format: 'percent' as const, align: 'right' as const },
      ]

      let totalTenderVal = 0
      let totalCertifiedVal = 0

      const rows = rawRows.map((b: any) => {
        const tenderQty = Number(b.tender_quantity) || 0
        const rate = Number(b.awarded_rate) || 0
        const certQty = Number(b.certified_quantity || b.measured_quantity) || 0
        const certAmount = certQty * rate
        const pct = tenderQty > 0 ? (certQty / tenderQty) * 100 : 0

        totalTenderVal += (Number(b.total_amount) || (tenderQty * rate))
        totalCertifiedVal += certAmount

        return {
          item_number: b.item_number || '-',
          description: b.description,
          unit: b.unit,
          tender_quantity: tenderQty,
          awarded_rate: rate,
          certified_quantity: certQty,
          certified_amount: certAmount,
          execution_percent: pct,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { certified_amount: totalCertifiedVal },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 3. BOQ PROGRESS
    // ─────────────────────────────────────────────────────────────────────────
    case 'BOQ_PROGRESS': {
      let boqQuery = supabase
        .from('boq_items')
        .select('*')
        .order('item_number')

      if (projectId && projectId !== 'all') boqQuery = boqQuery.eq('project_id', projectId)

      const { data: boqData } = await boqQuery
      const rawRows = boqData || []

      const columns = [
        { key: 'item_number', label: 'BOQ Item', align: 'left' as const },
        { key: 'description', label: 'Specification', align: 'left' as const },
        { key: 'unit', label: 'Unit', align: 'center' as const },
        { key: 'tender_quantity', label: 'Tender Qty', format: 'number' as const, align: 'right' as const },
        { key: 'awarded_rate', label: 'Rate (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'tender_amount', label: 'Tender Amount', format: 'currency' as const, align: 'right' as const },
        { key: 'executed_quantity', label: 'Executed Qty', format: 'number' as const, align: 'right' as const },
        { key: 'executed_amount', label: 'Executed Value', format: 'currency' as const, align: 'right' as const },
        { key: 'physical_percent', label: 'Physical %', format: 'percent' as const, align: 'right' as const },
        { key: 'financial_percent', label: 'Financial %', format: 'percent' as const, align: 'right' as const },
      ]

      let sumTender = 0
      let sumExecuted = 0

      const rows = rawRows.map((b: any) => {
        const tenderQty = Number(b.tender_quantity) || 0
        const rate = Number(b.awarded_rate) || 0
        const tenderVal = Number(b.total_amount) || (tenderQty * rate)
        const execQty = Number(b.certified_quantity || b.measured_quantity) || 0
        const execVal = execQty * rate
        const physPct = tenderQty > 0 ? (execQty / tenderQty) * 100 : 0
        const finPct = tenderVal > 0 ? (execVal / tenderVal) * 100 : 0

        sumTender += tenderVal
        sumExecuted += execVal

        return {
          item_number: b.item_number,
          description: b.description,
          unit: b.unit,
          tender_quantity: tenderQty,
          awarded_rate: rate,
          tender_amount: tenderVal,
          executed_quantity: execQty,
          executed_amount: execVal,
          physical_percent: physPct,
          financial_percent: finPct,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: {
          tender_amount: sumTender,
          executed_amount: sumExecuted,
          financial_percent: sumTender > 0 ? (sumExecuted / sumTender) * 100 : 0,
        },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 4. QUANTITY BALANCE
    // ─────────────────────────────────────────────────────────────────────────
    case 'QUANTITY_BALANCE': {
      let boqQuery = supabase
        .from('boq_items')
        .select('*')
        .order('item_number')

      if (projectId && projectId !== 'all') boqQuery = boqQuery.eq('project_id', projectId)

      const { data: boqData } = await boqQuery
      const rawRows = boqData || []

      const columns = [
        { key: 'item_number', label: 'Item No', align: 'left' as const },
        { key: 'description', label: 'Description', align: 'left' as const },
        { key: 'unit', label: 'Unit', align: 'center' as const },
        { key: 'tender_quantity', label: 'Tender Qty', format: 'number' as const, align: 'right' as const },
        { key: 'variation_quantity', label: 'Variation (+/-)', format: 'number' as const, align: 'right' as const },
        { key: 'revised_quantity', label: 'Revised Total', format: 'number' as const, align: 'right' as const },
        { key: 'measured_quantity', label: 'Executed to Date', format: 'number' as const, align: 'right' as const },
        { key: 'balance_quantity', label: 'Balance Qty', format: 'number' as const, align: 'right' as const },
        { key: 'balance_value', label: 'Balance Value (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'status', label: 'Deviation Status', format: 'badge' as const, align: 'center' as const },
      ]

      let totalBalanceVal = 0

      const rows = rawRows.map((b: any) => {
        const tenderQty = Number(b.tender_quantity) || 0
        const variationQty = Number(b.variation_quantity) || 0
        const revisedQty = b.revised_quantity ? Number(b.revised_quantity) : tenderQty + variationQty
        const measuredQty = Number(b.certified_quantity || b.measured_quantity) || 0
        const balanceQty = revisedQty - measuredQty
        const rate = Number(b.awarded_rate) || 0
        const balanceVal = Math.max(0, balanceQty) * rate
        totalBalanceVal += balanceVal

        let devStatus = 'Within Tender Limit'
        if (measuredQty > tenderQty * 1.25) {
          devStatus = 'Clause 12 Exceeded (>25%)'
        } else if (measuredQty > tenderQty) {
          devStatus = 'Deviated (>100%)'
        }

        return {
          item_number: b.item_number,
          description: b.description,
          unit: b.unit,
          tender_quantity: tenderQty,
          variation_quantity: variationQty,
          revised_quantity: revisedQty,
          measured_quantity: measuredQty,
          balance_quantity: balanceQty,
          balance_value: balanceVal,
          status: devStatus,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { balance_value: totalBalanceVal },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 5. RA BILL ABSTRACT
    // ─────────────────────────────────────────────────────────────────────────
    case 'RA_BILL_ABSTRACT': {
      let query = supabase
        .from('ra_bills')
        .select('*')
        .order('submission_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('submission_date', startDate)
      if (endDate) query = query.lte('submission_date', endDate)
      if (status && status !== 'ALL') query = query.eq('status', status)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'bill_number', label: 'RA Bill No', align: 'left' as const },
        { key: 'submission_date', label: 'Submission Date', format: 'date' as const, align: 'center' as const },
        { key: 'work_certified_amount', label: 'Gross Work Certified', format: 'currency' as const, align: 'right' as const },
        { key: 'retention_amount', label: 'Retention Withheld', format: 'currency' as const, align: 'right' as const },
        { key: 'net_payable_amount', label: 'Net Payable', format: 'currency' as const, align: 'right' as const },
        { key: 'amount_received', label: 'Amount Received', format: 'currency' as const, align: 'right' as const },
        { key: 'outstanding_balance', label: 'Outstanding Balance', format: 'currency' as const, align: 'right' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      let gross = 0, retention = 0, netPay = 0, received = 0, outstanding = 0

      const rows = rawRows.map((r: any) => {
        const g = Number(r.work_certified_amount) || 0
        const ret = Number(r.retention_amount) || 0
        const np = Number(r.net_payable_amount) || (g - ret)
        const rec = Number(r.amount_received) || 0
        const out = Number(r.outstanding_balance) || (np - rec)

        gross += g
        retention += ret
        netPay += np
        received += rec
        outstanding += out

        return {
          bill_number: r.bill_number,
          submission_date: r.submission_date,
          work_certified_amount: g,
          retention_amount: ret,
          net_payable_amount: np,
          amount_received: rec,
          outstanding_balance: out,
          status: (r.status || 'submitted').toUpperCase(),
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: {
          work_certified_amount: gross,
          retention_amount: retention,
          net_payable_amount: netPay,
          amount_received: received,
          outstanding_balance: outstanding,
        },
        availableStatuses: ['ALL', 'SUBMITTED', 'PASSED', 'PARTIALLY_PAID', 'FULLY_PAID'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 6. RA BILL REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'RA_BILL_REGISTER': {
      let query = supabase
        .from('ra_bills')
        .select('*')
        .order('submission_date', { ascending: true })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('submission_date', startDate)
      if (endDate) query = query.lte('submission_date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'bill_number', label: 'Bill No', align: 'left' as const },
        { key: 'submission_date', label: 'Submitted Date', format: 'date' as const, align: 'center' as const },
        { key: 'work_certified_amount', label: 'Gross Certified (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'net_payable_amount', label: 'Net Payable (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'status', label: 'Bill Status', format: 'badge' as const, align: 'center' as const },
        { key: 'date_received', label: 'Payment Date', format: 'date' as const, align: 'center' as const },
        { key: 'remarks', label: 'Auditor Remarks', align: 'left' as const },
      ]

      let sumGross = 0, sumNet = 0
      const rows = rawRows.map((r: any) => {
        const g = Number(r.work_certified_amount) || 0
        const n = Number(r.net_payable_amount) || 0
        sumGross += g
        sumNet += n
        return {
          bill_number: r.bill_number,
          submission_date: r.submission_date,
          work_certified_amount: g,
          net_payable_amount: n,
          status: (r.status || 'submitted').toUpperCase(),
          date_received: r.date_received || '-',
          remarks: r.remarks || '-',
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { work_certified_amount: sumGross, net_payable_amount: sumNet },
        availableStatuses: ['ALL', 'SUBMITTED', 'PASSED', 'PARTIALLY_PAID', 'FULLY_PAID'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 7. PAYMENT REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'PAYMENT_REGISTER': {
      let query = supabase
        .from('ra_bill_payments')
        .select(`
          id, payment_date, gross_amount, tds_amount, gst_tds_amount, labour_cess_amount,
          other_deductions, total_deductions, net_bank_amount, voucher_reference, remarks,
          ra_bills ( bill_number )
        `)
        .order('payment_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('payment_date', startDate)
      if (endDate) query = query.lte('payment_date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'voucher_reference', label: 'Treasury Voucher / UTR', align: 'left' as const },
        { key: 'payment_date', label: 'Payment Date', format: 'date' as const, align: 'center' as const },
        { key: 'bill_number', label: 'Against RA Bill', align: 'left' as const },
        { key: 'gross_amount', label: 'Gross Released (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'tds_amount', label: 'TDS (194C)', format: 'currency' as const, align: 'right' as const },
        { key: 'gst_tds_amount', label: 'GST-TDS (2%)', format: 'currency' as const, align: 'right' as const },
        { key: 'labour_cess_amount', label: 'Labour Cess (1%)', format: 'currency' as const, align: 'right' as const },
        { key: 'total_deductions', label: 'Total Deductions', format: 'currency' as const, align: 'right' as const },
        { key: 'net_bank_amount', label: 'Net Bank Credit (₹)', format: 'currency' as const, align: 'right' as const },
      ]

      let grossSum = 0, dedSum = 0, netSum = 0
      const rows = rawRows.map((r: any) => {
        const g = Number(r.gross_amount) || 0
        const d = Number(r.total_deductions) || 0
        const n = Number(r.net_bank_amount) || (g - d)
        grossSum += g
        dedSum += d
        netSum += n
        return {
          voucher_reference: r.voucher_reference || 'VOUCHER-CREDIT',
          payment_date: r.payment_date,
          bill_number: r.ra_bills?.bill_number || '-',
          gross_amount: g,
          tds_amount: Number(r.tds_amount) || 0,
          gst_tds_amount: Number(r.gst_tds_amount) || 0,
          labour_cess_amount: Number(r.labour_cess_amount) || 0,
          total_deductions: d,
          net_bank_amount: n,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { gross_amount: grossSum, total_deductions: dedSum, net_bank_amount: netSum },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 8. CONTRACT EVENT REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'CONTRACT_EVENT_REGISTER': {
      let query = supabase
        .from('contract_events')
        .select('*')
        .order('event_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('event_date', startDate)
      if (endDate) query = query.lte('event_date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'reference_number', label: 'Event Ref', align: 'left' as const },
        { key: 'event_date', label: 'Event Date', format: 'date' as const, align: 'center' as const },
        { key: 'title', label: 'Event Title / Subject', align: 'left' as const },
        { key: 'event_type', label: 'Category', align: 'center' as const },
        { key: 'responsibility', label: 'Responsibility', align: 'center' as const },
        { key: 'delay_days', label: 'Delay Impact (Days)', format: 'number' as const, align: 'right' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      let totalDays = 0
      const rows = rawRows.map((e: any) => {
        const days = Number(e.delay_days) || 0
        totalDays += days
        return {
          reference_number: e.reference_number || e.event_code || 'EVT-REC',
          event_date: e.event_date,
          title: e.title,
          event_type: e.event_type || e.category || 'General',
          responsibility: e.responsible_party || e.responsibility || 'Department',
          delay_days: days,
          status: (e.status || 'OPEN').toUpperCase(),
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { delay_days: totalDays },
        availableStatuses: ['ALL', 'OPEN', 'RESOLVED', 'CLOSED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 9. HINDRANCE REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'HINDRANCE_REGISTER': {
      let query = supabase
        .from('hindrances')
        .select('*')
        .order('start_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('start_date', startDate)
      if (endDate) query = query.lte('start_date', endDate)
      if (status && status !== 'ALL') query = query.eq('status', status)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'hindrance_number', label: 'Item No', align: 'left' as const },
        { key: 'description', label: 'Nature of Hindrance', align: 'left' as const },
        { key: 'cause', label: 'Cause / GCC Ground', align: 'left' as const },
        { key: 'responsible_party', label: 'Responsible Entity', align: 'center' as const },
        { key: 'start_date', label: 'Start Date', format: 'date' as const, align: 'center' as const },
        { key: 'end_date', label: 'Removal Date', format: 'date' as const, align: 'center' as const },
        { key: 'total_days', label: 'Total Days', format: 'number' as const, align: 'right' as const },
        { key: 'overlap_days', label: 'Overlap', format: 'number' as const, align: 'right' as const },
        { key: 'net_delay_days', label: 'Net Delay', format: 'number' as const, align: 'right' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      let netDelaySum = 0
      const rows = rawRows.map((h: any, idx: number) => {
        const net = Number(h.net_delay_days || h.days_delayed) || 0
        netDelaySum += net
        return {
          hindrance_number: h.hindrance_number || `#${idx + 1}`,
          description: h.description,
          cause: h.cause || h.category || 'Site Clearance / Land Acquisition',
          responsible_party: h.responsible_party || 'Employer / Department',
          start_date: h.start_date,
          end_date: h.end_date || 'Ongoing',
          total_days: Number(h.total_days || h.duration_days) || 0,
          overlap_days: Number(h.overlap_days) || 0,
          net_delay_days: net,
          status: (h.status || 'OPEN').toUpperCase(),
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { net_delay_days: netDelaySum },
        availableStatuses: ['ALL', 'OPEN', 'RESOLVED', 'CLOSED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 10. CORRESPONDENCE REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'CORRESPONDENCE_REGISTER': {
      let query = supabase
        .from('contract_correspondence')
        .select('*')
        .order('date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('date', startDate)
      if (endDate) query = query.lte('date', endDate)
      if (status && status !== 'ALL') query = query.eq('status', status)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'reference_number', label: 'Letter / Ref No', align: 'left' as const },
        { key: 'date', label: 'Date', format: 'date' as const, align: 'center' as const },
        { key: 'direction', label: 'Direction', format: 'badge' as const, align: 'center' as const },
        { key: 'sender', label: 'From', align: 'left' as const },
        { key: 'recipient', label: 'To', align: 'left' as const },
        { key: 'subject', label: 'Subject / Abstract', align: 'left' as const },
        { key: 'response_deadline', label: 'Response Deadline', format: 'date' as const, align: 'center' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      const rows = rawRows.map((c: any) => ({
        reference_number: c.reference_number || c.letter_number || '-',
        date: c.date,
        direction: (c.direction || 'OUTGOING').toUpperCase(),
        sender: c.sender,
        recipient: c.recipient,
        subject: c.subject,
        response_deadline: c.response_deadline || '-',
        status: (c.status || 'SENT').toUpperCase(),
      }))

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        availableStatuses: ['ALL', 'DRAFT', 'SENT', 'RECEIVED', 'ACKNOWLEDGED', 'RESPONSE_REQUIRED', 'RESPONDED', 'CLOSED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 11. NOTICE REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'NOTICE_REGISTER': {
      let query = supabase
        .from('contract_correspondence')
        .select('*')
        .or('is_notice.eq.true,subject.ilike.%notice%')
        .order('date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('date', startDate)
      if (endDate) query = query.lte('date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'reference_number', label: 'Notice Ref', align: 'left' as const },
        { key: 'date', label: 'Notice Date', format: 'date' as const, align: 'center' as const },
        { key: 'clause_reference', label: 'Clause Invoked', align: 'left' as const },
        { key: 'subject', label: 'Notice Description', align: 'left' as const },
        { key: 'sender', label: 'Served By', align: 'left' as const },
        { key: 'recipient', label: 'Served To', align: 'left' as const },
        { key: 'response_deadline', label: 'Contractual Deadline', format: 'date' as const, align: 'center' as const },
        { key: 'status', label: 'Compliance Status', format: 'badge' as const, align: 'center' as const },
      ]

      const rows = rawRows.map((n: any) => ({
        reference_number: n.reference_number || n.letter_number || '-',
        date: n.date,
        clause_reference: n.clause_reference || 'GCC Clause 5 / 12',
        subject: n.subject,
        sender: n.sender,
        recipient: n.recipient,
        response_deadline: n.response_deadline || 'Within 14 Days',
        status: (n.status || 'SERVED').toUpperCase(),
      }))

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        availableStatuses: ['ALL', 'SENT', 'RECEIVED', 'ACKNOWLEDGED', 'CLOSED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 12. EOT REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'EOT_REGISTER': {
      let query = supabase
        .from('contract_eot_cases')
        .select('*')
        .order('submission_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('start_date', startDate)
      if (endDate) query = query.lte('end_date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'eot_reference', label: 'EOT Case Ref', align: 'left' as const },
        { key: 'cause_summary', label: 'Primary Cause / Ground', align: 'left' as const },
        { key: 'start_date', label: 'Period From', format: 'date' as const, align: 'center' as const },
        { key: 'end_date', label: 'Period To', format: 'date' as const, align: 'center' as const },
        { key: 'days_claimed', label: 'Days Claimed', format: 'number' as const, align: 'right' as const },
        { key: 'days_approved', label: 'Days Approved', format: 'number' as const, align: 'right' as const },
        { key: 'pending_days', label: 'Pending Days', format: 'number' as const, align: 'right' as const },
        { key: 'revised_completion_date', label: 'Revised Date', format: 'date' as const, align: 'center' as const },
        { key: 'status', label: 'EOT Status', format: 'badge' as const, align: 'center' as const },
      ]

      let claimedSum = 0, approvedSum = 0, pendingSum = 0
      const rows = rawRows.map((e: any) => {
        const c = Number(e.claimed_days || e.days_claimed) || 0
        const a = Number(e.approved_days || e.days_approved) || 0
        const p = Number(e.pending_days) || Math.max(0, c - a)
        claimedSum += c
        approvedSum += a
        pendingSum += p

        return {
          eot_reference: e.eot_reference || 'EOT-01',
          cause_summary: e.cause || e.cause_summary || 'Department Hindrances & Site Delays',
          start_date: e.start_date,
          end_date: e.end_date,
          days_claimed: c,
          days_approved: a,
          pending_days: p,
          revised_completion_date: e.revised_completion_date || '-',
          status: (e.status || 'SUBMITTED').toUpperCase(),
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { days_claimed: claimedSum, days_approved: approvedSum, pending_days: pendingSum },
        availableStatuses: ['ALL', 'DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'PARTIALLY_APPROVED', 'REJECTED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 13. VARIATION REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'VARIATION_REGISTER': {
      let query = supabase
        .from('contract_variations')
        .select('*')
        .order('instruction_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('instruction_date', startDate)
      if (endDate) query = query.lte('instruction_date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'reference_number', label: 'VO Order No', align: 'left' as const },
        { key: 'type', label: 'Variation Type', format: 'badge' as const, align: 'center' as const },
        { key: 'instruction_authority', label: 'Sanction Authority', align: 'left' as const },
        { key: 'instruction_date', label: 'Date', format: 'date' as const, align: 'center' as const },
        { key: 'proposed_item_description', label: 'Item Scope', align: 'left' as const },
        { key: 'proposed_amount', label: 'Proposed Value (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'approved_amount', label: 'Approved Value (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      let propSum = 0, appSum = 0
      const rows = rawRows.map((v: any) => {
        const p = Number(v.proposed_amount) || 0
        const a = Number(v.approved_amount) || 0
        propSum += p
        appSum += a
        return {
          reference_number: v.reference_number,
          type: v.type,
          instruction_authority: v.instruction_authority,
          instruction_date: v.instruction_date,
          proposed_item_description: v.proposed_item_description,
          proposed_amount: p,
          approved_amount: a,
          status: v.status,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { proposed_amount: propSum, approved_amount: appSum },
        availableStatuses: ['ALL', 'PROPOSED', 'UNDER_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'BILLED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 14. EXTRA ITEM REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'EXTRA_ITEM_REGISTER': {
      let query = supabase
        .from('contract_variations')
        .select('*')
        .in('type', ['EXTRA_ITEM', 'SUBSTITUTED_ITEM'])
        .order('instruction_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'reference_number', label: 'Extra Item No', align: 'left' as const },
        { key: 'type', label: 'Classification', align: 'center' as const },
        { key: 'proposed_item_description', label: 'Non-Schedule Description', align: 'left' as const },
        { key: 'proposed_unit', label: 'Unit', align: 'center' as const },
        { key: 'proposed_rate', label: 'Market / Analyzed Rate', format: 'currency' as const, align: 'right' as const },
        { key: 'approved_rate', label: 'Sanctioned Rate', format: 'currency' as const, align: 'right' as const },
        { key: 'approved_amount', label: 'Sanctioned Amount (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'approved_order_number', label: 'Sanction Order No', align: 'left' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      let totalSanctioned = 0
      const rows = rawRows.map((ei: any) => {
        const amt = Number(ei.approved_amount) || 0
        totalSanctioned += amt
        return {
          reference_number: ei.reference_number,
          type: ei.type === 'EXTRA_ITEM' ? 'Extra Item (N/S)' : 'Substituted Item',
          proposed_item_description: ei.proposed_item_description,
          proposed_unit: ei.proposed_unit || 'nos',
          proposed_rate: Number(ei.proposed_rate) || 0,
          approved_rate: Number(ei.approved_rate) || 0,
          approved_amount: amt,
          approved_order_number: ei.approved_order_number || 'Under Determination',
          status: ei.status,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { approved_amount: totalSanctioned },
        availableStatuses: ['ALL', 'PROPOSED', 'UNDER_APPROVAL', 'APPROVED', 'BILLED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 15. CLAIM REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'CLAIM_REGISTER': {
      let query = supabase
        .from('contract_claims')
        .select('*')
        .order('claim_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('claim_date', startDate)
      if (endDate) query = query.lte('claim_date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'claim_number', label: 'Claim No', align: 'left' as const },
        { key: 'claim_type', label: 'Head of Claim', align: 'left' as const },
        { key: 'title', label: 'Factual Grounds', align: 'left' as const },
        { key: 'claim_date', label: 'Submission Date', format: 'date' as const, align: 'center' as const },
        { key: 'claimed_amount', label: 'Claimed (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'approved_amount', label: 'Awarded / Approved', format: 'currency' as const, align: 'right' as const },
        { key: 'paid_amount', label: 'Paid / Realized', format: 'currency' as const, align: 'right' as const },
        { key: 'outstanding_amount', label: 'Outstanding (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      let cSum = 0, aSum = 0, pSum = 0, oSum = 0
      const rows = rawRows.map((cl: any) => {
        const c = Number(cl.claimed_amount) || 0
        const a = Number(cl.approved_amount) || 0
        const p = Number(cl.paid_amount) || 0
        const o = Number(cl.outstanding_amount) || (c - p)
        cSum += c
        aSum += a
        pSum += p
        oSum += o
        return {
          claim_number: cl.claim_number,
          claim_type: cl.claim_type.replace(/_/g, ' '),
          title: cl.title,
          claim_date: cl.claim_date,
          claimed_amount: c,
          approved_amount: a,
          paid_amount: p,
          outstanding_amount: o,
          status: cl.status,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: {
          claimed_amount: cSum,
          approved_amount: aSum,
          paid_amount: pSum,
          outstanding_amount: oSum,
        },
        availableStatuses: ['ALL', 'DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'PAID', 'REJECTED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 16. EVIDENCE REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'EVIDENCE_REGISTER': {
      let query = supabase
        .from('evidence_vault')
        .select('*')
        .order('created_at', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('created_at', startDate)
      if (endDate) query = query.lte('created_at', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'evidence_code', label: 'Vault ID', align: 'left' as const },
        { key: 'type', label: 'Evidence Type', format: 'badge' as const, align: 'center' as const },
        { key: 'title', label: 'Document Title', align: 'left' as const },
        { key: 'document_date', label: 'Event Date', format: 'date' as const, align: 'center' as const },
        { key: 'source', label: 'Source Entity', align: 'left' as const },
        { key: 'uploaded_by', label: 'Recorded By', align: 'left' as const },
        { key: 'notes', label: 'Legal Relevance / Notes', align: 'left' as const },
      ]

      const rows = rawRows.map((e: any) => ({
        evidence_code: e.evidence_code || e.id.substring(0, 8),
        type: e.type || 'DOCUMENT',
        title: e.title,
        document_date: e.document_date || e.created_at,
        source: e.source || 'Site Engineer',
        uploaded_by: e.uploaded_by || 'Staff',
        notes: e.notes || e.description || '-',
      }))

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 17. LABOUR REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'LABOUR_REGISTER': {
      let query = supabase
        .from('attendance')
        .select(`
          id, date, status, workers ( name, category, daily_rate )
        `)
        .order('date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('date', startDate)
      if (endDate) query = query.lte('date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'date', label: 'Date', format: 'date' as const, align: 'center' as const },
        { key: 'worker_name', label: 'Worker Name', align: 'left' as const },
        { key: 'category', label: 'Skill Category', align: 'center' as const },
        { key: 'status', label: 'Attendance', format: 'badge' as const, align: 'center' as const },
        { key: 'daily_rate', label: 'Wage Rate (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'wages_earned', label: 'Wages Payable (₹)', format: 'currency' as const, align: 'right' as const },
      ]

      let totalWages = 0
      const rows = rawRows.map((att: any) => {
        const rate = Number(att.workers?.daily_rate) || 500
        const factor = att.status === 'present' ? 1 : att.status === 'half_day' ? 0.5 : 0
        const earned = rate * factor
        totalWages += earned
        return {
          date: att.date,
          worker_name: att.workers?.name || 'Labourer',
          category: (att.workers?.category || 'Unskilled').toUpperCase(),
          status: (att.status || 'present').toUpperCase(),
          daily_rate: rate,
          wages_earned: earned,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { wages_earned: totalWages },
        availableStatuses: ['ALL', 'PRESENT', 'HALF_DAY', 'ABSENT'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 18. MATERIAL REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'MATERIAL_REGISTER': {
      let query = supabase
        .from('inventory_items')
        .select('*')
        .order('name')

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'name', label: 'Material Name', align: 'left' as const },
        { key: 'category', label: 'Category', align: 'center' as const },
        { key: 'unit', label: 'Unit', align: 'center' as const },
        { key: 'current_stock', label: 'Current Stock', format: 'number' as const, align: 'right' as const },
        { key: 'reorder_level', label: 'Reorder Level', format: 'number' as const, align: 'right' as const },
        { key: 'stock_status', label: 'Stock Status', format: 'badge' as const, align: 'center' as const },
      ]

      const rows = rawRows.map((m: any) => {
        const stock = Number(m.current_stock || m.quantity) || 0
        const min = Number(m.reorder_level || m.minimum_quantity) || 10
        const status = stock <= min ? 'LOW STOCK' : 'ADEQUATE'
        return {
          name: m.name,
          category: m.category || 'Civil',
          unit: m.unit || 'nos',
          current_stock: stock,
          reorder_level: min,
          stock_status: status,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 19. MACHINERY LOG
    // ─────────────────────────────────────────────────────────────────────────
    case 'MACHINERY_LOG': {
      let query = supabase
        .from('machinery_logs')
        .select(`
          id, log_date, hours_worked, idle_hours, diesel_litres, remarks,
          machinery_assets ( name, reg_number, equipment_type )
        `)
        .order('log_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)
      if (startDate) query = query.gte('log_date', startDate)
      if (endDate) query = query.lte('log_date', endDate)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'log_date', label: 'Date', format: 'date' as const, align: 'center' as const },
        { key: 'equipment_name', label: 'Equipment / Machine', align: 'left' as const },
        { key: 'reg_number', label: 'Asset Reg No', align: 'center' as const },
        { key: 'hours_worked', label: 'Worked Hours', format: 'number' as const, align: 'right' as const },
        { key: 'idle_hours', label: 'Idle Hours', format: 'number' as const, align: 'right' as const },
        { key: 'diesel_litres', label: 'Fuel Consumed (Ltrs)', format: 'number' as const, align: 'right' as const },
        { key: 'remarks', label: 'Site Location / Log Remarks', align: 'left' as const },
      ]

      let workSum = 0, idleSum = 0, fuelSum = 0
      const rows = rawRows.map((ml: any) => {
        const w = Number(ml.hours_worked) || 0
        const i = Number(ml.idle_hours) || 0
        const f = Number(ml.diesel_litres) || 0
        workSum += w
        idleSum += i
        fuelSum += f
        return {
          log_date: ml.log_date,
          equipment_name: ml.machinery_assets?.name || 'Heavy Equipment',
          reg_number: ml.machinery_assets?.reg_number || '-',
          hours_worked: w,
          idle_hours: i,
          diesel_litres: f,
          remarks: ml.remarks || 'Site execution',
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { hours_worked: workSum, idle_hours: idleSum, diesel_litres: fuelSum },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 20. SUPPLIER STATEMENT
    // ─────────────────────────────────────────────────────────────────────────
    case 'SUPPLIER_STATEMENT': {
      let query = supabase
        .from('suppliers')
        .select('*')
        .order('name')

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'name', label: 'Supplier / Vendor', align: 'left' as const },
        { key: 'gstin', label: 'GSTIN', align: 'center' as const },
        { key: 'material_supplied', label: 'Primary Material', align: 'left' as const },
        { key: 'total_billed', label: 'Total Billed (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'total_paid', label: 'Total Paid (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'balance_payable', label: 'Outstanding Payable', format: 'currency' as const, align: 'right' as const },
      ]

      let billSum = 0, paidSum = 0, paySum = 0
      const rows = rawRows.map((s: any) => {
        const b = Number(s.total_billed) || 0
        const p = Number(s.total_paid) || 0
        const bal = Number(s.balance_payable) || Math.max(0, b - p)
        billSum += b
        paidSum += p
        paySum += bal
        return {
          name: s.name,
          gstin: s.gstin || '-',
          material_supplied: s.material_supplied || s.category || 'Civil Materials',
          total_billed: b,
          total_paid: p,
          balance_payable: bal,
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { total_billed: billSum, total_paid: paidSum, balance_payable: paySum },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 21. BG REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'BG_REGISTER': {
      let query = supabase
        .from('security_deposits')
        .select('*')
        .eq('deposit_type', 'bank_guarantee')
        .order('expiry_date', { ascending: true })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'reference_number', label: 'BG Number', align: 'left' as const },
        { key: 'issuing_bank', label: 'Issuing Bank & Branch', align: 'left' as const },
        { key: 'purpose', label: 'Guarantee Purpose', align: 'center' as const },
        { key: 'amount', label: 'BG Value (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'issue_date', label: 'Issue Date', format: 'date' as const, align: 'center' as const },
        { key: 'expiry_date', label: 'Expiry Date', format: 'date' as const, align: 'center' as const },
        { key: 'status', label: 'Status', format: 'badge' as const, align: 'center' as const },
      ]

      let totalBg = 0
      const rows = rawRows.map((bg: any) => {
        const amt = Number(bg.amount) || 0
        totalBg += amt
        return {
          reference_number: bg.reference_number || 'BG-001',
          issuing_bank: bg.issuing_bank || 'State Bank of India',
          purpose: bg.purpose || 'Performance Security',
          amount: amt,
          issue_date: bg.issue_date || bg.deposit_date,
          expiry_date: bg.expiry_date || bg.release_due_date,
          status: (bg.status || 'ACTIVE').toUpperCase(),
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { amount: totalBg },
        availableStatuses: ['ALL', 'ACTIVE', 'INVOKED', 'RELEASED', 'EXPIRED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 22. SECURITY DEPOSIT REGISTER
    // ─────────────────────────────────────────────────────────────────────────
    case 'SECURITY_DEPOSIT_REGISTER': {
      let query = supabase
        .from('security_deposits')
        .select('*')
        .order('deposit_date', { ascending: false })

      if (projectId && projectId !== 'all') query = query.eq('project_id', projectId)

      const { data } = await query
      const rawRows = data || []

      const columns = [
        { key: 'deposit_type', label: 'Deposit Instrument', format: 'badge' as const, align: 'center' as const },
        { key: 'reference_number', label: 'Receipt / FDR Ref', align: 'left' as const },
        { key: 'amount', label: 'Withheld Amount (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'deposit_date', label: 'Deposit Date', format: 'date' as const, align: 'center' as const },
        { key: 'release_due_date', label: 'DLP Release Date', format: 'date' as const, align: 'center' as const },
        { key: 'status', label: 'Refund Status', format: 'badge' as const, align: 'center' as const },
      ]

      let totalDeposit = 0
      const rows = rawRows.map((sd: any) => {
        const a = Number(sd.amount) || 0
        totalDeposit += a
        return {
          deposit_type: (sd.deposit_type || 'Retention').replace(/_/g, ' ').toUpperCase(),
          reference_number: sd.reference_number || '-',
          amount: a,
          deposit_date: sd.deposit_date,
          release_due_date: sd.release_due_date || 'Post-DLP',
          status: (sd.status || 'WITHHELD').toUpperCase(),
        }
      })

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { amount: totalDeposit },
        availableStatuses: ['ALL', 'WITHHELD', 'REFUNDED', 'FORFEITED'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 23. PROJECT COST REPORT
    // ─────────────────────────────────────────────────────────────────────────
    case 'PROJECT_COST_REPORT': {
      let expQuery = supabase
        .from('expenses')
        .select('*')
        .order('date', { ascending: false })

      if (projectId && projectId !== 'all') expQuery = expQuery.eq('project_id', projectId)
      if (startDate) expQuery = expQuery.gte('date', startDate)
      if (endDate) expQuery = expQuery.lte('date', endDate)

      const { data: expenses } = await expQuery
      const rawExpenses = expenses || []

      // Group expenses by category
      const categories: Record<string, number> = {}
      for (const e of rawExpenses) {
        const cat = e.category || 'General Site Overheads'
        categories[cat] = (categories[cat] || 0) + (Number(e.amount) || 0)
      }

      // If no expenses, insert baseline cost categories
      if (Object.keys(categories).length === 0) {
        categories['Civil Construction Materials'] = 0
        categories['Labour Muster & Wages'] = 0
        categories['Plant & Machinery Operating Cost'] = 0
        categories['Diesel & Fuel Consumption'] = 0
        categories['Site Supervision & Admin Overheads'] = 0
      }

      const totalCost = Object.values(categories).reduce((s, v) => s + v, 0)

      const columns = [
        { key: 'category', label: 'Cost Center / Expenditure Head', align: 'left' as const },
        { key: 'amount', label: 'Actual Incurred (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'percentage', label: 'Share of Total Cost', format: 'percent' as const, align: 'right' as const },
        { key: 'status', label: 'Budget Status', format: 'badge' as const, align: 'center' as const },
      ]

      const rows = Object.entries(categories).map(([cat, amt]) => ({
        category: cat,
        amount: amt,
        percentage: totalCost > 0 ? (amt / totalCost) * 100 : 0,
        status: 'ON TRACK',
      }))

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { amount: totalCost, percentage: 100 },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 24. PROJECT PROFITABILITY REPORT
    // ─────────────────────────────────────────────────────────────────────────
    case 'PROJECT_PROFITABILITY_REPORT': {
      // 1. Fetch Contract value
      const awardedVal = Number(projectData?.awarded_amount) || 5000000

      // 2. Fetch total work certified from RA Bills
      let billQuery = supabase.from('ra_bills').select('work_certified_amount, amount_received')
      if (projectId && projectId !== 'all') billQuery = billQuery.eq('project_id', projectId)
      const { data: bills } = await billQuery
      const certifiedSum = (bills || []).reduce((s, b) => s + (Number(b.work_certified_amount) || 0), 0)
      const receivedSum = (bills || []).reduce((s, b) => s + (Number(b.amount_received) || 0), 0)

      // 3. Fetch total expenses incurred
      let expQuery = supabase.from('expenses').select('amount')
      if (projectId && projectId !== 'all') expQuery = expQuery.eq('project_id', projectId)
      const { data: exp } = await expQuery
      const totalCostsIncurred = (exp || []).reduce((s, e) => s + (Number(e.amount) || 0), 0)

      const grossMargin = certifiedSum - totalCostsIncurred
      const grossMarginPct = certifiedSum > 0 ? (grossMargin / certifiedSum) * 100 : 0
      const pendingTreasuryReceivable = certifiedSum - receivedSum

      const columns = [
        { key: 'financial_metric', label: 'Financial Performance Head', align: 'left' as const },
        { key: 'amount', label: 'Financial Value (₹)', format: 'currency' as const, align: 'right' as const },
        { key: 'ratio', label: '% of Certified Billing', format: 'percent' as const, align: 'right' as const },
        { key: 'remarks', label: 'Contractor Commercial Analysis', align: 'left' as const },
      ]

      const rows = [
        {
          financial_metric: 'Tender Awarded Contract Value',
          amount: awardedVal,
          ratio: certifiedSum > 0 ? (awardedVal / certifiedSum) * 100 : 0,
          remarks: 'Original stipulated contractual value',
        },
        {
          financial_metric: 'Gross Work Certified to Date (e-MB Revenue)',
          amount: certifiedSum,
          ratio: 100.0,
          remarks: 'Earned value accepted by government authority',
        },
        {
          financial_metric: 'Cash Received from Treasury',
          amount: receivedSum,
          ratio: certifiedSum > 0 ? (receivedSum / certifiedSum) * 100 : 0,
          remarks: 'Liquid bank remittances realized against bills',
        },
        {
          financial_metric: 'Total Direct Project Costs Incurred',
          amount: totalCostsIncurred,
          ratio: certifiedSum > 0 ? (totalCostsIncurred / certifiedSum) * 100 : 0,
          remarks: 'Sum of materials, labour wages, machinery fuel & overheads',
        },
        {
          financial_metric: 'Contractor Gross Operating Margin',
          amount: grossMargin,
          ratio: grossMarginPct,
          remarks: grossMargin >= 0 ? 'Profitable site execution balance' : 'Operational overrun / cost deficit',
        },
        {
          financial_metric: 'Outstanding Government Receivables',
          amount: pendingTreasuryReceivable,
          ratio: certifiedSum > 0 ? (pendingTreasuryReceivable / certifiedSum) * 100 : 0,
          remarks: 'Approved running account bills awaiting department disbursement',
        },
      ]

      return {
        reportKey,
        reportTitle: def.title,
        category: def.category,
        orientation: def.orientation,
        metadata,
        columns,
        rows,
        totals: { amount: grossMargin, ratio: grossMarginPct },
        availableStatuses: ['ALL'],
        recordCount: rows.length,
      }
    }

    default:
      throw new Error(`Unsupported report key: ${reportKey}`)
  }
}
